name: "rl_crossing_stand_on"
save_scenario: False
t_start: 0.0
t_end: 300.0
dt_sim: 0.5
utm_zone: 33
map_size: [5000.0, 5000.0]
map_origin_enu: [39000.0, 6956450.0]
map_data_files: ["More_og_Romsdal_utm33.gdb"]
new_load_of_map_data: True
type: MS
n_random_ships: 3
episode_generation:
  n_episodes: 1
  n_constant_os_state_episodes: 1
  n_constant_os_plan_episodes: 1
  n_constant_do_state_episodes: 1
  n_plans_per_do_state: 1
  n_constant_disturbance_episodes: 1
  delta_uniform_position_sample: 100000

rl:
  action_type: "sbmpc_parameter_setting_and_solver_action"
  action_sample_time: 2.0
  observation_type:
    dict_observation:
      - "path_relative_navigation_observation"
      - "relative_tracking_observation"
      #- "time_observation"
      - "sbmpc_parameter_observation"

ship_list:
  - csog_state: [6957900.0, 40500.0, 10.0, 0.0]
    waypoints: [[6957900.0, 6960200.0], [40500.0, 40500.0]]
    speed_plan: [10.0, 10.0]
    id: 0
    mmsi: 100
    tracker:
      kf:
        P_0: [49.1, 49.1, 0.11, 0.11]
        q: 0.15
    sensors:
      - radar:
          max_range: 2000.0
          measurement_rate: 0.5
          R_ne: [30.0, 30.0]
          R_ne_true: [25.0, 25.0]
          R_polar_true: [64.0, 0.0003]
          generate_clutter: False
          clutter_cardinality_expectation: 5
          detection_probability: 0.95
          include_polar_meas_noise: False
      - ais:
          max_range: 5000.0
          ais_class: A
          R: [26.3, 26.3, 0.1, 0.1]
          R_true: [26.3, 26.3, 0.1, 0.1]
    guidance:
      los:
        pass_angle_threshold: 80.0
        R_a: 15.0
        K_p: 0.015
        K_i: 0.0
        max_cross_track_error_int: 200.0
        cross_track_error_int_threshold: 30.0
    controller:
      flsc:
        K_p_u: 3.0
        K_i_u: 0.3
        K_p_chi: 2.5
        K_d_chi: 3.0
        K_i_chi: 0.1
        max_speed_error_int: 4.0
        speed_error_int_threshold: 0.5
        max_chi_error_int: 90.0
        chi_error_int_threshold: 20.0
    model:
      telemetron: ''

  - csog_state: [6958400.0, 41550.0, 8.0, 320.0]
    waypoints: [[6958400.0, 6960000.0], [41550.0, 39600.0]]
    speed_plan: [8.0, 8.0]
    id: 1
    mmsi: 101
    tracker:
      kf:
        P_0: [49.1, 49.1, 0.11, 0.11]
        q: 0.15
    sensors:
      - radar:
          max_range: 2000.0
          measurement_rate: 0.5
          R_ne: [30.0, 30.0]
          R_ne_true: [25.0, 25.0]
          R_polar_true: [64.0, 0.0003]
          generate_clutter: False
          clutter_cardinality_expectation: 5
          detection_probability: 0.95
          include_polar_meas_noise: False
      - ais:
          max_range: 5000.0
          ais_class: A
          R: [26.3, 26.3, 0.1, 0.1]
          R_true: [26.3, 26.3, 0.1, 0.1]
    guidance:
      los:
        pass_angle_threshold: 80.0
        R_a: 15.0
        K_p: 0.015
        K_i: 0.0
        max_cross_track_error_int: 200.0
        cross_track_error_int_threshold: 30.0
    controller:
      flsc:
        K_p_u: 3.0
        K_i_u: 0.3
        K_p_chi: 2.5
        K_d_chi: 3.0
        K_i_chi: 0.1
        max_speed_error_int: 4.0
        speed_error_int_threshold: 0.5
        max_chi_error_int: 90.0
        chi_error_int_threshold: 20.0
    model:
      telemetron: ''

  - csog_state: [6958400.0, 39500.0, 8.0, 45.0]
    waypoints: [[6958400.0, 6960000.0], [39500.0, 41200.0]]
    speed_plan: [8.0, 8.0]
    id: 2
    mmsi: 102
    tracker:
      kf:
        P_0: [49.1, 49.1, 0.11, 0.11]
        q: 0.15
    sensors:
      - radar:
          max_range: 2000.0
          measurement_rate: 0.5
          R_ne: [30.0, 30.0]
          R_ne_true: [25.0, 25.0]
          R_polar_true: [64.0, 0.0003]
          generate_clutter: False
          clutter_cardinality_expectation: 5
          detection_probability: 0.95
          include_polar_meas_noise: False
      - ais:
          max_range: 5000.0
          ais_class: A
          R: [26.3, 26.3, 0.1, 0.1]
          R_true: [26.3, 26.3, 0.1, 0.1]
    guidance:
      los:
        pass_angle_threshold: 80.0
        R_a: 15.0
        K_p: 0.015
        K_i: 0.0
        max_cross_track_error_int: 200.0
        cross_track_error_int_threshold: 30.0
    controller:
      flsc:
        K_p_u: 3.0
        K_i_u: 0.3
        K_p_chi: 2.5
        K_d_chi: 3.0
        K_i_chi: 0.1
        max_speed_error_int: 4.0
        speed_error_int_threshold: 0.5
        max_chi_error_int: 90.0
        chi_error_int_threshold: 20.0
    model:
      telemetron: ''

  - csog_state: [6960200.0, 40500.0, 5.0, 180.0]
    waypoints: [[6960200.0, 6957900.0], [40500.0, 40500.0]]
    speed_plan: [5.0, 5.0]
    id: 3
    mmsi: 103
    tracker:
      kf:
        P_0: [49.1, 49.1, 0.11, 0.11]
        q: 0.15
    sensors:
      - radar:
          max_range: 2000.0
          measurement_rate: 0.5
          R_ne: [30.0, 30.0]
          R_ne_true: [25.0, 25.0]
          R_polar_true: [64.0, 0.0003]
          generate_clutter: False
          clutter_cardinality_expectation: 5
          detection_probability: 0.95
          include_polar_meas_noise: False
      - ais:
          max_range: 5000.0
          ais_class: A
          R: [26.3, 26.3, 0.1, 0.1]
          R_true: [26.3, 26.3, 0.1, 0.1]
    guidance:
      los:
        pass_angle_threshold: 80.0
        R_a: 15.0
        K_p: 0.015
        K_i: 0.0
        max_cross_track_error_int: 200.0
        cross_track_error_int_threshold: 30.0
    controller:
      flsc:
        K_p_u: 3.0
        K_i_u: 0.3
        K_p_chi: 2.5
        K_d_chi: 3.0
        K_i_chi: 0.1
        max_speed_error_int: 4.0
        speed_error_int_threshold: 0.5
        max_chi_error_int: 90.0
        chi_error_int_threshold: 20.0
    model:
      telemetron: ''